### ISSUE TITLE
CUDA index out of bounds error

### ISSUE THREAD

**Issue by nicolefeng2** [spectraldoy/music-transformer#6]
Hello! I am trying to train this music transformer model on a subset of ~100 MIDI files from MAESTRO v3.0. I ran the preprocessing script with lth=2048, and attempted to train the model with the following hparams:
hparams = {
    "d_model": 256,
    "num_layers": 6,
    "num_heads": 8,
    "d_ff": 1024,
    "max_rel_dist": 0,
    "max_abs_position": 0,
    "vocab_size": vocab_size,
    "bias": True,
    "dropout": 0.1,
    "layernorm_eps": 1e-6
}

However, I end up with the following error when I try to run train.py in colab with a T4:
unknown:0: unknown: block: [0,0,0], thread: [63,0,0] Assertion `index out of bounds: tl.full([XBLOCK], 0, tl.int32) < 0` failed.
Traceback (most recent call last):
  File "/content/drive/MyDrive/music-transformer/train.py", line 429, in <module>
    trainer.fit(args.epochs)
  File "/content/drive/MyDrive/music-transformer/train.py", line 298, in fit
    loss = train_step(model, self.optimizer, self.scheduler, train_inp, train_tar)
  File "/content/drive/MyDrive/music-transformer/train.py", line 102, in train_step
    predictions = model(inp, mask=create_mask(inp, n=inp.dim() + 2))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/music-transformer/model.py", line 82, in forward
    def forward(self, x, mask=None):
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 1100, in forward
    return compiled_fn(full_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 308, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/utils.py", line 124, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/utils.py", line 98, in g
    return f(*args)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1525, in forward
    fw_outs = call_func_at_runtime_with_args(
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/utils.py", line 124, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 488, in wrapper
    return compiled_fn(runtime_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 667, in inner_fn
    outs = compiled_fn(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 1478, in __call__
    return self.current_callable(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/utils.py", line 1977, in run
    return model(new_inputs)
  File "/tmp/torchinductor_root/bw/cbw6esbkxccis27yfouy4evfw7qmeqatf6ldmp3hdxklboliczi7.py", line 1465, in call
    triton_poi_fused_embedding_2.run(buf14, 256, grid=grid(256), stream=stream0)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 836, in run
    self.autotune_to_one_config(*args, grid=grid, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 729, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 704, in benchmark_all_configs
    timings = {
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 705, in <dictcomp>
    launcher: self.bench(launcher, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 675, in bench
    return benchmarker.benchmark_gpu(kernel_call, rep=40, fast_flush=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/benchmarking.py", line 66, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/benchmarking.py", line 201, in benchmark_gpu
    return self.triton_do_bench(_callable, **kwargs, return_mode="median")
  File "/usr/local/lib/python3.10/dist-packages/triton/testing.py", line 106, in do_bench
    fn()
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 663, in kernel_call
    launcher(
  File "<string>", line 13, in launcher
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/driver.py", line 365, in __call__
    self.launch(*args, **kwargs)
RuntimeError: Triton Error [CUDA]: device-side assert triggered

Does anyone know what could be causing this issue and how to fix it? I noticed that the inner shape of the data was not equal to 2048 --- is this expected?

@spectraldoy do you mind sharing what sequence length (lth) you used for preprocessing for your model4v2?

**Comment by nicolefeng2** [comment]
update: seems like this only occurs when I pass in 0 for max_rel_dist

**Comment by spectraldoy** [comment]
Hey, thanks for trying it out. The lth I used for my projects was always around 2000, but more on the actual error - that is a bug. There is code that assumes at least one relative distance embedding exists. The music transformer as such is really a relative attention transformer, and so I just baked in the assumption that users would use a nonzero max relative distance, and in my testing never used a max_rel_dist of 0. Not entirely sure off the top of my head how it could be fixed - I'm sure it would be simple, but the architecture of the model depends heavily on it. If you want to take a stab at fixing it, I'd be happy to review a PR, or if this is significantly impacting you I could also work on it. You could try a max rel dist of 1 in the meantime.

**Comment by nicolefeng2** [comment]
Ah thanks for the quick response! I was trying to get some baseline results (vanilla transformer with self-attention) before gathering performance metrics on the music transformer with relative attention to see compare how much better relative attention makes the model at generating music samples, which is why I was using a max_rel_dist of 0. As of right not it's not impacting me too much so no worries.

**Comment by spectraldoy** [comment]
Just a note from my experience: the quality of the produced samples depends much more on the data and how it is cut than on the specific parameters of the model architecture. I found it very difficult to get a generalized model on all of MAESTRO, but 39 pieces of Chopin turned out somewhat better, it could perfectly replicate 64 pieces of Bach, and it worked somewhat well on videogame music.

Diversity in the training data can be a little unhelpful in this case. For example, due to the way MIDI works, a virtuosic Chopin piece contains many many more tokens than a Bach piece, even if the latter takes longer to play. Cutting both into chunks of around 2000 tokens actually captures a different amount of time, and therefore a different notion of musical development, which the model finds difficult to generalize across. Diversity across eras and composer accentuates this problem (which is a design issue on my part, we should be cutting based on time, not tokenized sequence length). In particular when I trained on music from after 1870 together with music from 1750-1830, the model was not able to converge. If we did not have the hardware limitations that force cutting to some standard length, then I suspect we would not have this issue.

But all of this just to caution, you'll get more stable results with a less diverse dataset, which will help you create a solid baseline.
